name: Alison Adare
favicon: null
layout_spectrum: 0.28460533870384097
typography_spectrum: 0.5252886596135795
title: Alison Adare
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdf5ea'
    - '#fa9900'
    - '#616161'
    - '#b75400'
  brandStrength: 1
  lightness: 0.7930760541930795
  saturation: 0.03436356713064015
  rhythmicContrast: 0.75
purpose: []
